### ISSUE TITLE
E2E tests failing with Cache not found for input keys

### ISSUE THREAD

**Issue by rohanKanojia** [jkubeio/jkube-integration-tests#243]
This morning I'm seeing unrelated failures in all E2E tests, it seems to be happening in all tests:
```
Run JKUBE_VERSION=$(mvn -f jkube/pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) \
POM file jkube/pom.xml specified with the -f/--file command line argument does not exist
```

These are the PRs I updated this morning:
- https://github.com/eclipse/jkube/pull/1995
- https://github.com/eclipse/jkube/pull/2065
- https://github.com/eclipse/jkube/pull/1984
- https://github.com/eclipse/jkube/pull/1686

**Comment by rohanKanojia** [comment]
It looks like there is some problem related to loading `jkube/` cache:
```
Run actions/cache@v2
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/jkubeio/ci/actions/runs/4193076077/jobs/7331414563#step:3:11)-[11](https://github.com/jkubeio/ci/actions/runs/4193076077/jobs/7331414563#step:3:12)-github-actions-deprecating-save-state-and-set-output-commands/
Cache not found for input keys: cache-e2e-bootstrap-4193076077
```

**Comment by rohanKanojia** [comment]
Similar issues seem to be created in GitHub Actions cache repository in past few days:
- https://github.com/actions/cache/issues/1116
- https://github.com/actions/cache/issues/1110

**Comment by rohanKanojia** [comment]
The issue is still there even after merging this fix. Need to think of something else.

**Comment by manusa** [comment]
From what I've seen, it seems that the problem is related to the Runner VM and the version of zstd.

**Comment by rohanKanojia** [comment]
We can either add another step for downgrading zstd to 1.5.0 or wait for this PR to get merged https://github.com/actions/cache/pull/1118

**Comment by manusa** [comment]
> We can either add another step for downgrading zstd to 1.5.0 or wait for this PR to get merged [actions/cache#1118](https://github.com/actions/cache/pull/1118)

Let's wait a couple of hours and see if they merge it. Else we can implement the temporary workaround.

**Comment by rohanKanojia** [comment]
The abovementioned PR seems to have been merged. Let me try to bump actions/cache to this revision

**Comment by rohanKanojia** [comment]
Not sure why but i still see failures after restarting some workflows

**Comment by rohanKanojia** [comment]
I think we need to do it on jkubeio/ci as well, as pointed by Marc in https://github.com/jkubeio/jkube-integration-tests/pull/244#issuecomment-1437272726

Okay, on E2E workflows I see actions/v2 getting used. Looks like they're picked from jkubeio/ci repository:
![Screenshot from 2023-02-21 19-38-46](https://user-images.githubusercontent.com/13834498/220367905-5e8086f4-acd9-41b1-9434-f730f974edb8.png)
